### ISSUE TITLE
Great work! Where is the inference code?

### ISSUE THREAD

**Issue by xiaozhi2015** [fireflyHunter/OpenNMT-Livebot#1]

**Comment by xiaozhi2015** [comment]
translate.py

**Comment by zhouwei5113** [comment]
> translate.py

Have you got the inference code？How did you use 'translate.py'? @xiaozhi2015

**Comment by xiaozhi2015** [comment]
in translate.py

> > translate.py
> 
> Have you got the inference code？How did you use 'translate.py'? @xiaozhi2015

in translate.py
